// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDos45Xxud5K-vf6UCa4_UXEBoZfofj3zY',
    appId: '1:578932370896:web:bb0af8ced043448b191dd5',
    messagingSenderId: '578932370896',
    projectId: 'crux-notes-1656c',
    authDomain: 'crux-notes-1656c.firebaseapp.com',
    storageBucket: 'crux-notes-1656c.firebasestorage.app',
    measurementId: 'G-MMLKD2C067',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApdlUr71_ctt3VfpYt2Bw3DjANd2v3JjY',
    appId: '1:578932370896:android:9a5dbdeb0985d15f191dd5',
    messagingSenderId: '578932370896',
    projectId: 'crux-notes-1656c',
    storageBucket: 'crux-notes-1656c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO0CsGGidUr1_03PZnslmKEkK8u8xaW90',
    appId: '1:578932370896:ios:0a1704d77e2087bd191dd5',
    messagingSenderId: '578932370896',
    projectId: 'crux-notes-1656c',
    storageBucket: 'crux-notes-1656c.firebasestorage.app',
    iosClientId: '578932370896-j1kgn1d52gdv8l6pmsdshjpe855doi47.apps.googleusercontent.com',
    iosBundleId: 'com.example.cruxNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO0CsGGidUr1_03PZnslmKEkK8u8xaW90',
    appId: '1:578932370896:ios:0a1704d77e2087bd191dd5',
    messagingSenderId: '578932370896',
    projectId: 'crux-notes-1656c',
    storageBucket: 'crux-notes-1656c.firebasestorage.app',
    iosClientId: '578932370896-j1kgn1d52gdv8l6pmsdshjpe855doi47.apps.googleusercontent.com',
    iosBundleId: 'com.example.cruxNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDos45Xxud5K-vf6UCa4_UXEBoZfofj3zY',
    appId: '1:578932370896:web:4d2a963642092b57191dd5',
    messagingSenderId: '578932370896',
    projectId: 'crux-notes-1656c',
    authDomain: 'crux-notes-1656c.firebaseapp.com',
    storageBucket: 'crux-notes-1656c.firebasestorage.app',
    measurementId: 'G-TXT49QH0QR',
  );
}
